# Generated by Django 4.1.3 on 2022-12-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
